version: '3'

services:
  web:
    build: .
    ports:
      - "7000:7000"
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=emailapi.settings.base
  db:
    # Use an empty container for SQLite
    image: busybox
    volumes:
      - ./db.sqlite3:/code/db.sqlite3
