# Generated by Django 5.0.3 on 2024-04-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SalesSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("net_sales", models.DecimalField(decimal_places=2, max_digits=10)),
                ("gross_sales", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_product_sales",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("taxable_sales", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "non_taxable_sales",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("crv_charges", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_service_fees",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "taxable_service_fee",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "non_taxable_service_fees",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "shipping_and_handling",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_discounts",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "item_discounts",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "order_discounts",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_tax_and_surcharges",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("sales_tax", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "prevailing_tax",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "tax_rounding_variance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "pass_through_fee_tax",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("surcharges", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "crv_charges_liabilities",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("house_account", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payments_against_house_account",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "payments_with_house_account",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("gift_cards", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sold_value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "redeemed_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "store_credit_accrued",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "store_credit_redeemed",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("deposits", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "deposit_payments",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "applied_deposits",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
    ]
