# Generated by Django 5.0.4 on 2024-04-07 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SalesSummary",
        ),
    ]
